# Generated by Django 5.2.4 on 2025-07-23 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address_user_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('INSTRUCTOR', 'Instructor'), ('STUDENT', 'Student')], max_length=20),
        ),
    ]
