# Generated by Django 5.2.4 on 2025-07-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_published_status'),
        ('students', '0003_remove_student_course_student_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
