# Generated by Django 5.2.4 on 2025-07-19 09:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('a0f0f46b-95ad-49f8-bb56-7148db2db3a6'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('9e68486c-2144-49de-a099-d6a75883ff5b'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
