# Generated by Django 5.2.4 on 2025-07-19 10:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5ccdf5fc-d360-4f18-83e1-b00f0e8ccc1c'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d44c6394-4671-43d6-abb7-080d02747326'), editable=False, primary_key=True, serialize=False),
        ),
    ]
