# Generated by Django 5.2.4 on 2025-07-19 10:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0002_alter_category_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3936cb5a-996d-4c76-9066-f17062f7dcdd'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b71a5eda-3cc7-48bf-b5ef-0a98471f2b72'), editable=False, primary_key=True, serialize=False),
        ),
    ]
