# Generated by Django 5.2.4 on 2025-07-20 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0003_alter_category_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('602bdc93-9bcc-4430-aa43-dcdfbed6b9fe'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('45dd0805-0dfb-4e90-9efc-3af72385d6c2'), editable=False, primary_key=True, serialize=False),
        ),
    ]
