# Generated by Django 5.2.4 on 2025-07-20 03:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0004_alter_category_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0e400732-1fcc-4799-abfc-be5c7a4ec3b0'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4820269e-047f-49a8-9b81-760b5a3e8de5'), editable=False, primary_key=True, serialize=False),
        ),
    ]
