# Generated by Django 5.2.4 on 2025-07-20 14:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0005_alter_category_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c97b2a02-88ec-4708-9507-1410033c2945'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66fd18d7-7da8-4e26-b4e4-5b5891fad85e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
