# Generated by Django 5.2.4 on 2025-07-20 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizers', '0006_alter_category_id_alter_tag_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.UUIDField(default=uuid.UUID('d9193059-a4d9-4cca-9011-a7c6e7f9e465'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='tag',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ec2ddc67-187d-4f0f-b276-a291146f7344'), editable=False, primary_key=True, serialize=False),
        ),
    ]
