# Generated by Django 5.2.4 on 2025-07-20 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='course/covers/'),
        ),
    ]
