# Generated by Django 5.2.4 on 2025-07-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_course_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='course/covers/'),
        ),
    ]
