# Generated by Django 5.2.4 on 2025-07-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_remove_course_instructor_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='published_status',
        ),
    ]
