# Generated by Django 5.2.4 on 2025-07-21 08:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_alter_course_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField()),
                ('video', models.URLField(blank=True, help_text='Embed URL (e.g., YouTube or Vimeo link)', null=True)),
                ('pdf', models.FileField(blank=True, help_text='Upload a PDF file for the lesson', null=True, upload_to='lessons/files/')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.course')),
            ],
        ),
    ]
